# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pn5.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pn5.proto',
  package='',
  serialized_pb=_b('\n\tpn5.proto\"/\n\x06PIndex\x12\x13\n\x0bpatient_key\x18\x01 \x02(\t\x12\x10\n\x08position\x18\x02 \x02(\x03\"5\n\x06VIndex\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x10\n\x08position\x18\x02 \x02(\x03\x12\x0c\n\x04meta\x18\x03 \x01(\x05\"Q\n\x05IMeta\x12\r\n\x05index\x18\x01 \x02(\x05\x12\r\n\x05\x66type\x18\x05 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\"k\n\tIndexFile\x12\x19\n\x08patients\x18\x01 \x03(\x0b\x32\x07.PIndex\x12\x17\n\x06visits\x18\x02 \x03(\x0b\x32\x07.VIndex\x12\x18\n\x08metadata\x18\x03 \x03(\x0b\x32\x06.IMeta\x12\x10\n\x08\x66ilename\x18\x04 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PINDEX = _descriptor.Descriptor(
  name='PIndex',
  full_name='PIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='patient_key', full_name='PIndex.patient_key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='PIndex.position', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=60,
)


_VINDEX = _descriptor.Descriptor(
  name='VIndex',
  full_name='VIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='VIndex.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='VIndex.position', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta', full_name='VIndex.meta', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=115,
)


_IMETA = _descriptor.Descriptor(
  name='IMeta',
  full_name='IMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='IMeta.index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ftype', full_name='IMeta.ftype', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='year', full_name='IMeta.year', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='IMeta.dtype', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='IMeta.state', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=198,
)


_INDEXFILE = _descriptor.Descriptor(
  name='IndexFile',
  full_name='IndexFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='patients', full_name='IndexFile.patients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visits', full_name='IndexFile.visits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='IndexFile.metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='IndexFile.filename', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=307,
)

_INDEXFILE.fields_by_name['patients'].message_type = _PINDEX
_INDEXFILE.fields_by_name['visits'].message_type = _VINDEX
_INDEXFILE.fields_by_name['metadata'].message_type = _IMETA
DESCRIPTOR.message_types_by_name['PIndex'] = _PINDEX
DESCRIPTOR.message_types_by_name['VIndex'] = _VINDEX
DESCRIPTOR.message_types_by_name['IMeta'] = _IMETA
DESCRIPTOR.message_types_by_name['IndexFile'] = _INDEXFILE

PIndex = _reflection.GeneratedProtocolMessageType('PIndex', (_message.Message,), dict(
  DESCRIPTOR = _PINDEX,
  __module__ = 'pn5_pb2'
  # @@protoc_insertion_point(class_scope:PIndex)
  ))
_sym_db.RegisterMessage(PIndex)

VIndex = _reflection.GeneratedProtocolMessageType('VIndex', (_message.Message,), dict(
  DESCRIPTOR = _VINDEX,
  __module__ = 'pn5_pb2'
  # @@protoc_insertion_point(class_scope:VIndex)
  ))
_sym_db.RegisterMessage(VIndex)

IMeta = _reflection.GeneratedProtocolMessageType('IMeta', (_message.Message,), dict(
  DESCRIPTOR = _IMETA,
  __module__ = 'pn5_pb2'
  # @@protoc_insertion_point(class_scope:IMeta)
  ))
_sym_db.RegisterMessage(IMeta)

IndexFile = _reflection.GeneratedProtocolMessageType('IndexFile', (_message.Message,), dict(
  DESCRIPTOR = _INDEXFILE,
  __module__ = 'pn5_pb2'
  # @@protoc_insertion_point(class_scope:IndexFile)
  ))
_sym_db.RegisterMessage(IndexFile)


# @@protoc_insertion_point(module_scope)
